import Head from 'next/head'

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-100 p-6">
      <Head>
        <title>خدمات زيت السيارة</title>
      </Head>

      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-6 text-center">خدمات زيت محرك السيارات</h1>

        <div className="bg-white rounded-2xl shadow p-6 mb-6">
          <h2 className="text-xl font-semibold mb-4">أدخل بيانات سيارتك</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block mb-1 font-medium">الاسم</label>
              <input type="text" placeholder="مثال: أحمد محمد" className="w-full border rounded p-2" />
            </div>
            <div>
              <label className="block mb-1 font-medium">نوع السيارة</label>
              <input type="text" placeholder="مثال: تويوتا كورولا" className="w-full border rounded p-2" />
            </div>
            <div>
              <label className="block mb-1 font-medium">القراءة الحالية للعداد (كم)</label>
              <input type="number" placeholder="مثال: 150000" className="w-full border rounded p-2" />
            </div>
            <div>
              <label className="block mb-1 font-medium">نوع الزيت المستخدم</label>
              <input type="text" placeholder="مثال: 10W-40" className="w-full border rounded p-2" />
            </div>
          </div>
          <button className="mt-4 bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700">حفظ البيانات</button>
        </div>

        <div className="bg-white rounded-2xl shadow p-6">
          <h2 className="text-xl font-semibold mb-4">قراءات تغيير الزيت</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>القراءة الأولى: 145000 كم - زيت 10W-40</li>
            <li>القراءة الثانية: 150000 كم - زيت 10W-40</li>
            <li className="text-green-600">الموعد المتوقع للتغيير القادم: 155000 كم</li>
          </ul>
        </div>
      </div>
    </div>
  )
}
